<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard Summary</title>
    <style>
        body { font-family: 'Inter', sans-serif; color: #111827; margin: 0; padding: 32px; }
        h1, h2 { color: #0f172a; }
        .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }
        .card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        th { background: #f8fafc; font-weight: 600; }
        .muted { color: #6b7280; font-size: 0.9rem; }
        .mt-4 { margin-top: 16px; }
    </style>
</head>
<body>
    <h1>Mekodonia Admin Report</h1>
    <p class="muted">
        Generated by {{ $generatedBy->name }} on {{ $generatedAt->format('F j, Y H:i') }}<br>
        Branch: {{ $filters['branch_id'] ? '#'.$filters['branch_id'] : 'All branches' }} · Range: last {{ $filters['date_range'] }} days
    </p>

    <div class="grid mt-4">
        <div class="card">
            <h2>Totals</h2>
            <p>Total Sponsorships: <strong>{{ $stats['total_sponsorships'] ?? 0 }}</strong></p>
            <p>Total Elders: <strong>{{ $stats['total_elders'] ?? 0 }}</strong></p>
            <p>Total Donors: <strong>{{ $stats['total_donors'] ?? 0 }}</strong></p>
            <p>Monthly Expenses Covered: <strong>{{ number_format($stats['monthly_expenses_covered'] ?? 0, 2) }} ETB</strong></p>
        </div>
        <div class="card">
            <h2>Performance</h2>
            <p>Promise Fulfillment: <strong>{{ number_format($stats['promise_fulfillment_rate'] ?? 0, 2) }}%</strong></p>
            <p>Missed Payments: <strong>{{ $stats['missed_payments'] ?? 0 }}</strong></p>
            <p>Guest Donations Today: <strong>{{ number_format($stats['guest_donations_today'] ?? 0, 2) }} ETB</strong></p>
        </div>
    </div>

    <div class="card mt-4">
        <h2>Relationship Distribution</h2>
        <table>
            <thead>
            <tr>
                <th>Relationship</th>
                <th>Active Sponsorships</th>
            </tr>
            </thead>
            <tbody>
            @forelse(($stats['relationship_distribution'] ?? []) as $relationship => $count)
                <tr>
                    <td>{{ ucfirst($relationship) }}</td>
                    <td>{{ $count }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2" class="muted">No relationship data available for this filter.</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>

    <div class="card mt-4">
        <h2>Monthly Donations Trend</h2>
        <table>
            <thead>
            <tr>
                <th>Month</th>
                <th>Total Donations (ETB)</th>
            </tr>
            </thead>
            <tbody>
            @forelse(($trend ?? []) as $point)
                <tr>
                    <td>{{ $point['label'] }}</td>
                    <td>{{ number_format($point['amount'] ?? 0, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2" class="muted text-center">No donations reported yet.</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>

    <div class="card mt-4">
        <h2>Recent Activity</h2>
        @forelse(($stats['recent_activity'] ?? []) as $activity)
            <p>
                <strong>{{ $activity['description'] }}</strong><br>
                <span class="muted">{{ $activity['time_ago'] }}</span>
            </p>
            @unless($loop->last)
                <hr style="border:none;border-top:1px solid #e5e7eb;margin:12px 0;">
            @endunless
        @empty
            <p class="muted">No recent activity logged yet.</p>
        @endforelse
    </div>
</body>
</html>
